#7 PATCH Beta
staceycoils/backend_project pull request #2
Opened 2022-02-17 10:26 UTC by staceycoils

Added tests for PATCH /api/articles/:article_id, added functionality to code for PATCH to this endpoint.

2022-02-17 11:28 UTC, jimstev2447 requested changes

2022-02-17 11:28 UTC, jimstev2447 commented on __tests__/app.test.js
> +})
I think we might be missing a test or two here, think about errors that could come with the request body, basically anything a user can touch could cause an error :)

2022-02-17 16:08 UTC, sirKevlar commented
PR Ticket#7 - nearly there.
I think we would need one more test to catch error when the patch object has the wrong key eg {inc_votrew: 10}

Side note:
I noticed this test for articlesById...
"Status 204 when valid but empty :article_id"
This is a 404(not found) rather than a 204(created)

2022-02-18 11:11 UTC, dav3rid approved these changes

2022-02-18 11:12 UTC, merged